package com.ananoesis.shell.ai;

import java.lang.reflect.Method;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.mock;
import org.springframework.ai.chat.messages.AssistantMessage;

import com.ananoesis.shell.service.ConversationService;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * {@link AgentContextBuilder} 解析方法的分支覆盖。
 *
 * <p>WHY 独立测试：parseToolCalls/parseToolCallsForSpring 的 null/blank/
 * 非法 JSON/缺失字段等分支未被覆盖。</p>
 */
@DisplayName("AgentContextBuilder 解析方法分支覆盖")
class AgentContextBuilderParseTest {

    private final ObjectMapper objectMapper = new ObjectMapper();
    private AgentContextBuilder builder;

    @BeforeEach
    void setUp() {
        ContextTokenEstimator estimator = mock(ContextTokenEstimator.class);
        builder = new AgentContextBuilder(
                mock(ConversationService.class), objectMapper, estimator);
    }

    @Nested
    @DisplayName("parseToolCalls（反射）")
    class ParseToolCalls {
        @SuppressWarnings("unchecked")
        private List<Map<String, Object>> invoke(String json) throws Exception {
            Method m = AgentContextBuilder.class.getDeclaredMethod("parseToolCalls", String.class);
            m.setAccessible(true);
            return (List<Map<String, Object>>) m.invoke(builder, json);
        }

        @Test
        @DisplayName("null 返回空列表")
        void nullReturnsEmpty() throws Exception {
            assertThat(invoke(null)).isEmpty();
        }

        @Test
        @DisplayName("空串返回空列表")
        void blankReturnsEmpty() throws Exception {
            assertThat(invoke("")).isEmpty();
        }

        @Test
        @DisplayName("空白串返回空列表")
        void whitespaceReturnsEmpty() throws Exception {
            assertThat(invoke("   ")).isEmpty();
        }

        @Test
        @DisplayName("合法 JSON 解析成功")
        void validJsonParsed() throws Exception {
            String json = "[{\"id\":\"call_1\",\"name\":\"run_command\",\"arguments\":\"{}\"}]";
            List<Map<String, Object>> result = invoke(json);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).get("id")).isEqualTo("call_1");
        }

        @Test
        @DisplayName("非法 JSON 返回空列表（不抛异常）")
        void invalidJsonReturnsEmpty() throws Exception {
            assertThat(invoke("not-json")).isEmpty();
        }

        @Test
        @DisplayName("空数组返回空列表")
        void emptyArrayReturnsEmpty() throws Exception {
            assertThat(invoke("[]")).isEmpty();
        }
    }

    @Nested
    @DisplayName("parseToolCallsForSpring（反射）")
    class ParseToolCallsForSpring {
        @SuppressWarnings("unchecked")
        private List<AssistantMessage.ToolCall> invoke(String json) throws Exception {
            Method m = AgentContextBuilder.class.getDeclaredMethod("parseToolCallsForSpring", String.class);
            m.setAccessible(true);
            return (List<AssistantMessage.ToolCall>) m.invoke(builder, json);
        }

        @Test
        @DisplayName("null 返回空列表")
        void nullReturnsEmpty() throws Exception {
            assertThat(invoke(null)).isEmpty();
        }

        @Test
        @DisplayName("合法 JSON 解析为 ToolCall 列表")
        void validJsonParsed() throws Exception {
            String json = "[{\"id\":\"call_1\",\"name\":\"run_command\",\"arguments\":\"{}\"}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).id()).isEqualTo("call_1");
            assertThat(result.get(0).name()).isEqualTo("run_command");
        }

        @Test
        @DisplayName("id 为空时自动生成 call_N")
        void blankIdAutoGenerated() throws Exception {
            String json = "[{\"id\":\"\",\"name\":\"run_command\",\"arguments\":\"{}\"}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).id()).startsWith("call_");
        }

        @Test
        @DisplayName("id 为 null 时自动生成 call_N")
        void nullIdAutoGenerated() throws Exception {
            String json = "[{\"name\":\"run_command\",\"arguments\":\"{}\"}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).id()).startsWith("call_");
        }

        @Test
        @DisplayName("name 为空白的条目被跳过")
        void blankNameSkipped() throws Exception {
            String json = "[{\"id\":\"call_1\",\"name\":\"\",\"arguments\":\"{}\"}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).isEmpty();
        }

        @Test
        @DisplayName("name 为 null 的条目被跳过")
        void nullNameSkipped() throws Exception {
            String json = "[{\"id\":\"call_1\",\"arguments\":\"{}\"}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).isEmpty();
        }

        @Test
        @DisplayName("arguments 非 String 时默认 {}")
        void nonStringArgumentsDefaults() throws Exception {
            String json = "[{\"id\":\"call_1\",\"name\":\"cmd\",\"arguments\":123}]";
            List<AssistantMessage.ToolCall> result = invoke(json);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).arguments()).isEqualTo("{}");
        }
    }

    @Nested
    @DisplayName("nullToEmpty（反射）")
    class NullToEmpty {
        @Test
        @DisplayName("null 返回空串")
        void nullReturnsEmpty() throws Exception {
            Method m = AgentContextBuilder.class.getDeclaredMethod("nullToEmpty", String.class);
            m.setAccessible(true);
            assertThat(m.invoke(null, (String) null)).isEqualTo("");
        }

        @Test
        @DisplayName("非 null 原样返回")
        void nonNullReturned() throws Exception {
            Method m = AgentContextBuilder.class.getDeclaredMethod("nullToEmpty", String.class);
            m.setAccessible(true);
            assertThat(m.invoke(null, "hello")).isEqualTo("hello");
        }
    }
}
